// Generated by CoffeeScript 1.4.0
(function() {
  var PigeonLogger;

  PigeonLogger = (function() {

    function PigeonLogger() {
      document.addEventListener('deviceready', this.deviceready, false);
    }

    PigeonLogger.prototype.deviceready = function(e) {
      return alert("deviceready");
    };

    PigeonLogger.prototype.capturePhoto = function() {
      var captureError, captureSuccess;
      captureSuccess = function(mediaFiles) {
        var i, img, _i, _ref, _results;
        navigator.notification.alert("Total files: " + mediaFiles.length);
        _results = [];
        for (i = _i = 0, _ref = mediaFiles.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          img = document.createElement('img');
          img.src = mediaFiles[i].fullPath;
          _results.push(document.body.appendChild(img));
        }
        return _results;
      };
      captureError = function(error) {
        return navigator.notification.alert("Error code: " + error.code, null, "Capture Error");
      };
      return navigator.device.capture.captureImage(captureSuccess, captureError, {
        limit: 2
      });
    };

    return PigeonLogger;

  })();

  window.app = new PigeonLogger();

}).call(this);
